In [3]:
import numpy as np

In [8]:
import torch
import time

# Set the matrix size
matrix_size = 1000

# Generate two random matrices
A = torch.randn(matrix_size, matrix_size)
B = torch.randn(matrix_size, matrix_size)

# Function to perform matrix multiplication on CPU
def cpu_matrix_multiplication(A, B):
    # Ensure tensors are on the CPU
    A = A.to('cpu')
    B = B.to('cpu')
    
    start_time = time.time()
    result = torch.mm(A, B)
    end_time = time.time()
    
    return end_time - start_time, result

# Function to perform matrix multiplication on GPU
def gpu_matrix_multiplication(A, B):
    # Ensure tensors are on the GPU
    A = A.to('mps')  # Use 'mps' for Metal Performance Shaders on M1/M2
    B = B.to('mps')
    
    # Warm-up to ensure accurate timing
    torch.mm(A, B)
    
    # Perform matrix multiplication
    start_time = time.time()
    result = torch.mm(A, B)
    end_time = time.time()
    
    return end_time - start_time, result

# Perform the matrix multiplication on CPU
cpu_time, res_cpu = cpu_matrix_multiplication(A, B)
print(f"CPU Time: {cpu_time:.6f} seconds")

# Perform the matrix multiplication on GPU
gpu_time, res_gpu = gpu_matrix_multiplication(A, B)
print(f"GPU Time (using MPS): {gpu_time:.6f} seconds")

# Compare the results
speedup = cpu_time / gpu_time
print(f"Speedup using GPU (MPS): {speedup:.2f}x")



CPU Time: 0.011079 seconds
GPU Time (using MPS): 0.000132 seconds
Speedup using GPU (MPS): 83.88x
tensor(0.0188)


# forward

In [35]:
X1=np.array([[1,2,3],[4,5,6]])
W1=np.array([[6,7],[3,3],[2,2]])
Y1=X1@W1
f=lambda x: x+1
df=lambda x: np.ones(x.shape)
y_out=f(Y1)
L=np.sum(y_out,axis=1)

In [36]:
X1

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
W1

array([[6, 7],
       [3, 3],
       [2, 2]])

In [38]:
Y1

array([[18, 19],
       [51, 55]])

In [39]:
y_out

array([[19, 20],
       [52, 56]])

In [40]:
L

array([ 39, 108])

# backward

In [41]:
dL_dyout=np.ones((2,2))
dyout_Y1=df(Y1)
Y1_W1=X1.T


In [42]:
dL_dyout

array([[1., 1.],
       [1., 1.]])

In [43]:
dyout_Y1

array([[1., 1.],
       [1., 1.]])

In [47]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
W*X

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
(x*w1+1)+(x*w2+1)

In [ ]:
X*W^T

In [ ]:
N_batch=3
N_yout=5

dL_dyout=(3,5)

x_in=(3,8)
W=(8,5)

c=dL_dyout*f_prime=(3,5)

x_in.T*c=(8,3)*(3,5)

